# Generated by Django 5.1.7 on 2025-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cpf',
            field=models.CharField(max_length=50, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='dataNascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='funcao',
            field=models.CharField(max_length=50, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='sexo',
            field=models.BooleanField(default=False, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
