# Generated by Django 5.1.7 on 2025-04-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_alter_voluntario_options_alter_voluntario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
