# Generated by Django 5.1.7 on 2025-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
