# Generated by Django 5.1.7 on 2025-04-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_evento_voluntario'),
        ('voluntario', '0002_alter_voluntario_options_alter_voluntario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_gerenciados', to='voluntario.voluntario', verbose_name='Gerente do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=50, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Evento'),
        ),
    ]
