# Generated by Django 5.1.7 on 2025-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_alter_evento_options_evento_gerente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('legenda', models.TextField()),
                ('imagem', models.ImageField(upload_to='posts/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
