# Generated by Django 5.1.7 on 2025-05-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='evento.post'),
        ),
    ]
