# Generated by Django 5.1.7 on 2025-05-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_evento_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='post',
        ),
    ]
