# Generated by Django 5.1.7 on 2025-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_alter_evento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
